/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as RulesDotmdRouteImport } from './routes/rules[.]md'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ApiCheckoutRouteImport } from './routes/api.checkout'
import { Route as ApiResolveRouteImport } from './routes/api.resolve'
import { Route as ApiStatsRouteImport } from './routes/api.stats'
import { Route as GoListingIdRouteImport } from './routes/go.$listingId'
import { Route as ReceiptsIntentIdRouteImport } from './routes/receipts.$intentId'
import { Route as ApiMockSettleRouteImport } from './routes/api.mock.settle'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api.webhooks.stripe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesDotmdRoute = RulesDotmdRouteImport.update({
  id: '/rules.md',
  path: '/rules.md',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResolveRoute = ApiResolveRouteImport.update({
  id: '/api/resolve',
  path: '/api/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const GoListingIdRoute = GoListingIdRouteImport.update({
  id: '/go/$listingId',
  path: '/go/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIntentIdRoute = ReceiptsIntentIdRouteImport.update({
  id: '/receipts/$intentId',
  path: '/receipts/$intentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockSettleRoute = ApiMockSettleRouteImport.update({
  id: '/api/mock/settle',
  path: '/api/mock/settle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rules': typeof RulesRoute
  '/rules.md': typeof RulesDotmdRoute
  '/stats': typeof StatsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/resolve': typeof ApiResolveRoute
  '/api/stats': typeof ApiStatsRoute
  '/go/$listingId': typeof GoListingIdRoute
  '/receipts/$intentId': typeof ReceiptsIntentIdRoute
  '/api/mock/settle': typeof ApiMockSettleRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rules': typeof RulesRoute
  '/rules.md': typeof RulesDotmdRoute
  '/stats': typeof StatsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/resolve': typeof ApiResolveRoute
  '/api/stats': typeof ApiStatsRoute
  '/go/$listingId': typeof GoListingIdRoute
  '/receipts/$intentId': typeof ReceiptsIntentIdRoute
  '/api/mock/settle': typeof ApiMockSettleRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rules': typeof RulesRoute
  '/rules.md': typeof RulesDotmdRoute
  '/stats': typeof StatsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/resolve': typeof ApiResolveRoute
  '/api/stats': typeof ApiStatsRoute
  '/go/$listingId': typeof GoListingIdRoute
  '/receipts/$intentId': typeof ReceiptsIntentIdRoute
  '/api/mock/settle': typeof ApiMockSettleRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rules'
    | '/rules.md'
    | '/stats'
    | '/api/checkout'
    | '/api/resolve'
    | '/api/stats'
    | '/go/$listingId'
    | '/receipts/$intentId'
    | '/api/mock/settle'
    | '/api/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rules'
    | '/rules.md'
    | '/stats'
    | '/api/checkout'
    | '/api/resolve'
    | '/api/stats'
    | '/go/$listingId'
    | '/receipts/$intentId'
    | '/api/mock/settle'
    | '/api/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/rules'
    | '/rules.md'
    | '/stats'
    | '/api/checkout'
    | '/api/resolve'
    | '/api/stats'
    | '/go/$listingId'
    | '/receipts/$intentId'
    | '/api/mock/settle'
    | '/api/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RulesRoute: typeof RulesRoute
  RulesDotmdRoute: typeof RulesDotmdRoute
  StatsRoute: typeof StatsRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiResolveRoute: typeof ApiResolveRoute
  ApiStatsRoute: typeof ApiStatsRoute
  GoListingIdRoute: typeof GoListingIdRoute
  ReceiptsIntentIdRoute: typeof ReceiptsIntentIdRoute
  ApiMockSettleRoute: typeof ApiMockSettleRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules.md': {
      id: '/rules.md'
      path: '/rules.md'
      fullPath: '/rules.md'
      preLoaderRoute: typeof RulesDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resolve': {
      id: '/api/resolve'
      path: '/api/resolve'
      fullPath: '/api/resolve'
      preLoaderRoute: typeof ApiResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$listingId': {
      id: '/go/$listingId'
      path: '/go/$listingId'
      fullPath: '/go/$listingId'
      preLoaderRoute: typeof GoListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/$intentId': {
      id: '/receipts/$intentId'
      path: '/receipts/$intentId'
      fullPath: '/receipts/$intentId'
      preLoaderRoute: typeof ReceiptsIntentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/settle': {
      id: '/api/mock/settle'
      path: '/api/mock/settle'
      fullPath: '/api/mock/settle'
      preLoaderRoute: typeof ApiMockSettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RulesRoute: RulesRoute,
  RulesDotmdRoute: RulesDotmdRoute,
  StatsRoute: StatsRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiResolveRoute: ApiResolveRoute,
  ApiStatsRoute: ApiStatsRoute,
  GoListingIdRoute: GoListingIdRoute,
  ReceiptsIntentIdRoute: ReceiptsIntentIdRoute,
  ApiMockSettleRoute: ApiMockSettleRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
